Pull in types from DefinitelyTyped
cheeriojs/cheerio pull request #1491
Opened 2020-09-25 22:28 UTC by paulmelnikow

This is an attempt to pull in the Cheerio types from DefintelyTyped so that they're available to all JS users, and so TS + JS users are assured that the type definitions match the version of the library they are using without having to determine the correct version of the @types/cheerio package.

It's the first time I've done this, so feedback from knowledgeable people would be very welcome.

I have two specific questions:

1. I've added `@types/node` to dependencies because the types use `Buffer`. Does the library target the browser and React Native? If so will including `@types/node` as a dependency cause problems? Is it preferable to use [a reference](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html)?
2. In DT, the type defs close with `declare module 'cheerio'`. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe3e8016d42f86fff607a7cd424ec3cabeea4b45/types/cheerio/index.d.ts#L304-L307 That wasn't working, so I've changed it here to `export = cheerioModule` which seems to work. Is there a better way to do that?

Before this is merged and shipped we should definitely test that the types can be used successfully by a dependent package. After this is shipped, the @types/cheerio package should be deprecated, and the DT types which depend on Cheerio updated accordingly. I'm not totally sure how to do that, but if someone can point me in the right direction I'm happy to do it.

/cc @matthewmueller @ljharb

Ref #1471

2020-09-26 05:44 UTC, ljharb requested changes

2020-09-26 05:44 UTC, ljharb commented on package.json
> +    "@types/node": "^14.11.2",
adding TS things to deps is a *very bad idea* since the vast majority of consumers are not using TS.

2020-09-26 05:44 UTC, ljharb commented
Specifically, shipping types with a package is also a very bad idea - types should only EVER be shipped via DT.

2020-09-26 17:03 UTC, fb55 commented
> shipping types with a package is also a very bad idea - types should only EVER be shipped via DT

Modules written in TS have always shipped with types, I don't think this is out of the norm. Any particular reason why we shouldn't ship types with cheerio?

Regarding the @types/node dependency: Ideally we'd work around pulling this in for all users. One possible solution would be to use `Uint8Array` as the type, as `Buffer` extends this nowadays. This is the approach eg. [uWebSockets](https://github.com/uNetworking/uWebSockets.js) follows.

2020-09-26 19:06 UTC, ljharb commented
Cheerio isn’t authored in typescript though.

One huge problem with it is that you conflate two APIs into the same semver. Needing to make a major bump to cheerio in order to make a breaking change to the types has very bad downstream effects. There’s a reason yargs 15 started shipping types and 16 removed them.

2020-09-27 02:32 UTC, paulmelnikow commented
An advantage of shipping the types with the library is it's easier for downstream users to match the types to the version of the library they are actually using. That's been a plus for nock. Breaking changes to types in DT aren't even tracked with semver (i.e. they ship in what would be patch releases) so I'm not convinced DT provides a perfect solution to the question of whether to version the JS API or the types. I'd be interested in the discussions that led to the decision for yargs.

> Needing to make a major bump to cheerio in order to make a breaking change to the types has very bad downstream effects.

What are the bad effects?

2020-09-27 02:41 UTC, ljharb commented
A semver major bump discourages updates, because of the risk of migration effort.

TS users have chosen “not JavaScript” and as such, they have signed up for the extra effort that entails. It is unacceptable to burden JavaScript users because some people choose to use an alternative language.

2020-09-28 18:19 UTC, paulmelnikow commented
> A semver major bump discourages updates, because of the risk of migration effort.

A changelog helps with this by clarifying what is affected by the semver major.

> TS users have chosen “not JavaScript” and as such, they have signed up for the extra effort that entails. It is unacceptable to burden JavaScript users because some people choose to use an alternative language.

I'm not sure it's as simple as this. The maintainer's motivation for this PR in #1471 was to improve the VS Code autocompletion for JavaScript users. Maintainers' time should be considered too. As the API changes, maintaining the types within the project is easier than doing it in DT because the changes can be made and tested in the same PR. Shipping the types here is especially important for the contributor workflow for TS users. Developing on or maintaining a fork is much harder when the types are external.

I get that there are some negatives to shipping the types within packages, including meaningful negatives for some users who might not ever care about TS, however completely insulating these users from the fact that TS exists seems short-sighted, given the easier maintenance and significant benefits for TS users and many JS users who unknowingly use the TS-driven autocompletion in VS Code.

2020-09-28 18:51 UTC, ljharb commented
Wait, if the project isn't authored in TS, how are the types tested in this project?

2020-09-28 19:45 UTC, paulmelnikow commented
As in DT, this PR checks in tests. In PRs that change the interface, the type changes are tested too.

When a TS project uses Cheerio as a dependency, and modifies the library and its interface, the type changes are necessary for testing the library changes within the context of the project.

2020-10-02 18:05 UTC, fb55 commented
Thanks a lot @paulmelnikow and @ljharb for finding an agreement here and getting to a better solution in the process!

Quite a few of the underlying packages for this module already have type definitions. Would it make sense to eg. replace the `Element` class with the exported class from `domhandler`?

2020-10-02 18:21 UTC, ljharb commented
@fb55 to be clear, I still don't think types should be shipped in a non-TS package, but it's also not up to me.

2020-10-02 19:09 UTC, paulmelnikow commented
> @fb55 to be clear, I still don't think types should be shipped in a non-TS package,

Yup, hope I didn't imply we'd somehow resolved our differences here 😁

2020-10-02 22:53 UTC, paulmelnikow commented
> Quite a few of the underlying packages for this module already have type definitions. Would it make sense to eg. replace the `Element` class with the exported class from `domhandler`?

Hmm, yes, it seems possible that would be better and seems a little odd that wasn't done before. I see cheerio requires htmlparser2 `^3` which transitively requires domhandler `^3`. Since all those types are shipped with those libraries, it's straightforward to depend on them.

Does cheerio have a way of shipping beta releases? The types I've pulled in here are identical to the last release in DT, though if we're going to make breaking changes to them, it probably would be good to validate them through beta releases.

2020-10-02 23:36 UTC, fb55 commented
> Does cheerio have a way of shipping beta releases?

The last couple of releases were RCs, which should have been beta versions realistically. I'm okay with making breaking changes to the types before the final `1.0.0` release.

> I still don't think types should be shipped in a non-TS package

That does make sense. For context: I'd like to transition cheerio to TS eventually, and having the type definitions ready will be helpful.

2020-10-03 00:24 UTC, paulmelnikow commented
> The last couple of releases were RCs, which should have been beta versions realistically. I'm okay with making breaking changes to the types before the final `1.0.0` release.

Ahhh gotcha! I didn't realize cheerio was already in the midst of 1.0 prereleases.

Would you like me to update this to use the upstream types?

2020-10-12 20:02 UTC, merged

2020-10-12 20:02 UTC, fb55 commented
I didn't really consider the fact that we have two different parsers in my earlier comments. Let's go with what we have right now, and adjust as we go. Thanks a lot @paulmelnikow for following through here!